---
abstract: 'portlets to show ticket counters per user'
author:
  - 'Ruslan Zakirov <Ruslan.Zakirov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SummaryByUser
no_index:
  directory:
    - html
    - inc
requires:
  DBIx::SearchBuilder: 1.56
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
